version: '1.0'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nextjs13-curso
    ports:
      - '3000:3000'
    volumes:
    - .:/app
    - /app/node_modules
